name: train-model
on: [push]
jobs:
  model-training:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Repository
      - uses: actions/checkout@v3
      - name: Setup Python environment
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt
      - name: Train model
      - run: python notepads/train.py
      - name: upload trained model
      - uses: actions/upload-artifact@v3
        with:
            name: saved_objects.pkl
            path: data/models/saved_objects.pkl

